// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuoCgSQ1Vk0LxYv-MOoGSOIzpJIfEqk0M',
    appId: '1:607424767081:web:9c43a529804690ebfc6ef8',
    messagingSenderId: '607424767081',
    projectId: 'awj-app-e5077',
    authDomain: 'awj-app-e5077.firebaseapp.com',
    storageBucket: 'awj-app-e5077.appspot.com',
    measurementId: 'G-EN8S3BXNV7',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bTEn-9RMqyT0gUqLyidYDF1FIeTZLXI',
    appId: '1:607424767081:android:38ffa44dfeeb8c25fc6ef8',
    messagingSenderId: '607424767081',
    projectId: 'awj-app-e5077',
    storageBucket: 'awj-app-e5077.appspot.com',
  );
}
